[package]
name = "friendgrow"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
diesel = { version = "1.4.8", features = [ "sqlite" ] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
structopt = "0.3.23"
priority-queue = "1.2.0"
